export type IColorType =
    | "purple"
    | "transpaernt"
    | "white"
    | "gray-light"
    | "gray-default"
    | "gray-dark"
    | "red"
    | "red-dark"
    | "purple-dark" 
    | "yellow"
    | "yellow-dark"
