import type { Metadata } from "next";
import "@/public/styles/globals.scss";
import { Container } from "@/features/_common/Container";
import { Navigation } from "@/features/_common/Navigation";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-background-gray-default">
        <Container>
          <Navigation />
          {children}
        </Container>
      </body>
    </html>
  );
}
